### ISSUE TITLE
Clarify license, potentially replace Fatal_Error

### ISSUE THREAD

**Issue by mk-pmb** [xeyownt/xseticon#12]
Between the lines `// FROM programs/xlsfonts/dsimple.c` and `// END FROM`, we currently have the functions

* `Fatal_Error`
* `Window_With_Name`
* `Select_Window_Args`
* `Select_Window_Mouse`

However, I can only find `Fatal_Error` in [Ubuntu's source of `xlsfonts/dsimple.c`](https://git.launchpad.net/ubuntu/+source/x11-utils/tree/xlsfonts/dsimple.c).

Are the others your own creation? Then we should adjust the END FROM marker.

Even better would be to write our own `Fatal_Error` function as well, because I can't currently see license compatibility.

Maybe it would suffice to have `Fatal_Error` be a trivial function that just prints the error message, and a comment for where to find a fancier function (e.g. the Ubuntu link above) if someone wants to make a temporary debug build.

**Comment by mk-pmb** [comment]
It might even be possible to add a CLI option to dynamically load the fancy `Fatal_Error` from `xlsfonts` on systems where the latter is installed.

**Comment by mk-pmb** [comment]
A fork that entirely omits the section in question [is now available](https://github.com/mk-pmb/xseticon-pmb).

**Comment by xeyownt** [comment]
TBH I have no idea of the origin of the license claim since this code is not mine.
I just hosted here because I used the tool at some time, and it was nowhere to be found.
I mailed the author and never got any reaction.

I doubt however that the claim was for the fatal_error function because this function is too generic (you find these everywhere).

But happy to see the project being forked ;-)
